<?php

namespace HostingBundle\Repository;

/**
 * HostingPeriodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HostingPeriodRepository extends \Doctrine\ORM\EntityRepository
{
}
