<?php

namespace ArtisanatBundle\Repository;

/**
 * priceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class priceRepository extends \Doctrine\ORM\EntityRepository
{
}
