<?php

namespace ActiviteBundle\Repository;

/**
 * activiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class activiteRepository extends \Doctrine\ORM\EntityRepository
{
}
