<?php

namespace ActiviteBundle\Repository;

/**
 * periodeActiviteDispoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class periodeActiviteDispoRepository extends \Doctrine\ORM\EntityRepository
{
}
