<?php

namespace SpearfishBundle\Repository;

/**
 * DiverRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiverRepository extends \Doctrine\ORM\EntityRepository
{
}
