<?php

namespace SpearfishBundle\Repository;

/**
 * FishspotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FishspotRepository extends \Doctrine\ORM\EntityRepository
{
}
