<?php

namespace SpearfishBundle\Repository;

/**
 * FishRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FishRepository extends \Doctrine\ORM\EntityRepository
{
}
