<?php

namespace SpearfishBundle\Repository;

/**
 * PoissonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PoissonRepository extends \Doctrine\ORM\EntityRepository
{
}
