<?php

namespace SpearfishBundle\Repository;

/**
 * speventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class speventRepository extends \Doctrine\ORM\EntityRepository
{
}
