<?php

namespace SpearfishBundle\Repository;

/**
 * SpotrateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpotrateRepository extends \Doctrine\ORM\EntityRepository
{
}
