<?php

namespace SpearfishBundle\Repository;

/**
 * SpotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpotRepository extends \Doctrine\ORM\EntityRepository
{
}
