<?php

namespace HikingBundle\Repository;

/**
 * Participation_EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Participation_EventRepository extends \Doctrine\ORM\EntityRepository
{


}
